#!/bin/bash
if [ "$#" == 0 ]; then
	if [ ! -f "./target/ParkingService.jar" ]; then
		./mvnw clean install;
	fi
	clear
	java -jar ./target/ParkingService.jar;
else
	if [ ! -f "./target/ParkingService.jar" ]; then
		./mvnw clean install
	fi
	clear
	if [ ! -f "$1" ]; then
		echo "Given input file name ($1) is not exists"
		exit 1
    	fi
	java -jar ./target/ParkingService.jar "$1"
fi
